# Generated by Django 5.2.5 on 2025-10-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [
                    ("manage_blog", "Может управлять публикациями в блоге")
                ],
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блогов",
            },
        ),
    ]
